[project]
name = "palaver-client"
version = "0.1.0"
requires-python = ">=3.12"
authors = [
    { name = "Dennis Parker", email = "dennis@windhavengroup.com" }
]

dependencies = [
    "httpx",  # For REST clients
    "websockets",  # For WebSocket handling
    "fire",
    "palaver-shared",
]
[tool.uv.sources]
palaver-shared= { path = "../shared" , editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
packages=["src/palaver_client"]
