[project]
name = "listener"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5",
    "sounddevice>=0.5.3",
    "soundfile>=0.13.1",
]
